[package]
org= "ballerinax"
name= "azure_cosmosdb"
version= "2.0.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true
