[package]
org= "ballerinax"
name= "azure_cosmosdb"
version= "1.0.1"
authors = ["Ballerina"]
keywords = ["azure", "cosmosdb", "database"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true

