[package]
distribution = "2201.1.0"
org= "ballerinax"
name= "azure_cosmosdb"
version= "3.0.1"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true

[[platform.java11.dependency]]
path = "../cosmosdb-native/build/libs/cosmosdb-native-3.0.1.jar"
groupId = "io.ballerinax"
artifactId = "cosmosdb"
version = "3.0.1"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns"
version = "4.1.77.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.77.Final"
